Update proto_compilation.yml

diff --git a/.github/workflows/proto_compilation.yml b/.github/workflows/proto_compilation.yml
--- a/.github/workflows/proto_compilation.yml
+++ b/.github/workflows/proto_compilation.yml
@@ -89,14 +89,19 @@ jobs:
           Protos/*.proto
         
         # Compile for Go
+        echo "Compiling Go files..."
+        echo "Protos directory contents:"
+        ls -la Protos
+        
+        echo "Running protoc command..."
         protoc -I=Protos \
           --go_out=GeneratedClients/go \
           --go_opt=paths=source_relative \
           --go-grpc_out=GeneratedClients/go \
           --go-grpc_opt=paths=source_relative \
-          --proto_path=Protos \
-          --go_opt=MProtos/parser.proto=github.com/ScalableDataIntegration/GeneratedClients/go \
-          Protos/*.proto
+          --go_opt=MProtos/parser.proto=github.com/JonasKaad/ScalableDataIntegration/GeneratedClients/go \
+          Protos/*.proto \
+        || { echo "protoc command failed"; exit 1; }
     
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v5
